/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;



import javax.swing.JButton;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JTextField;


/**
 *
 * @author Gabriela
 */
public class Biblioteca1 extends javax.swing.JFrame {
    
    public Biblioteca1() { 
         initComponents();

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtBuscar = new javax.swing.JTextField();
        jBtnBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMnNuevoSocio = new javax.swing.JMenuItem();
        jMnIngresarUs = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMnPrestarLibro = new javax.swing.JMenuItem();
        jMnIngresarLibro = new javax.swing.JMenuItem();
        jMnUbiLibro = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMnSociosNoConfiables = new javax.swing.JMenuItem();
        jMnListaSocio = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 191, 125));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.setToolTipText("");
        jPanel1.setAutoscrolls(true);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 3, 48)); // NOI18N
        jLabel1.setText("Biblioteca B.G");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        jTxtBuscar.setBackground(new java.awt.Color(233, 247, 245));
        jTxtBuscar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jTxtBuscar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(jTxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 500, 40));

        jBtnBuscar.setBackground(new java.awt.Color(241, 169, 89));
        jBtnBuscar.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jBtnBuscar.setText("Buscar");
        jBtnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jBtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 110, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 454));

        jMenuBar1.setBackground(new java.awt.Color(241, 169, 89));

        jMenu.setBackground(new java.awt.Color(247, 191, 125));
        jMenu.setText("Usuario");

        jMnNuevoSocio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnNuevoSocio.setText("Nuevo Socio");
        jMenu.add(jMnNuevoSocio);

        jMnIngresarUs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnIngresarUs.setText("Ingresar ");
        jMenu.add(jMnIngresarUs);

        jMenuBar1.add(jMenu);

        jMenu2.setBackground(new java.awt.Color(247, 191, 125));
        jMenu2.setText("Libro");

        jMnPrestarLibro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnPrestarLibro.setText("Prestar Libro");
        jMenu2.add(jMnPrestarLibro);

        jMnIngresarLibro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnIngresarLibro.setText("Ingresar Libro");
        jMenu2.add(jMnIngresarLibro);

        jMnUbiLibro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnUbiLibro.setText("Ubicacion Libro");
        jMnUbiLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnUbiLibroActionPerformed(evt);
            }
        });
        jMenu2.add(jMnUbiLibro);

        jMenuBar1.add(jMenu2);

        jMenu6.setBackground(new java.awt.Color(247, 191, 125));
        jMenu6.setText("Biblioteca");

        jMnSociosNoConfiables.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnSociosNoConfiables.setText("Socios no Confiables");
        jMenu6.add(jMnSociosNoConfiables);

        jMnListaSocio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnListaSocio.setText("Conocer Lista de socios");
        jMnListaSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnListaSocioActionPerformed(evt);
            }
        });
        jMenu6.add(jMnListaSocio);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnListaSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnListaSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnListaSocioActionPerformed

    private void jMnUbiLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnUbiLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnUbiLibroActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biblioteca1().setVisible(true);
            }
        });
    }

    public JButton getjBtnBuscar() {
        return jBtnBuscar;
    }



    

    public JMenuItem getjMnIngresarLibro() {
        return jMnIngresarLibro;
    }

    public JMenuItem getjMnIngresarUs() {
        return jMnIngresarUs;
    }

    public JMenuItem getjMnListaSocio() {
        return jMnListaSocio;
    }

    public JMenuItem getjMnPrestarLibro() {
        return jMnPrestarLibro;
    }

    public JMenuItem getjMnSociosNoConfiables() {
        return jMnSociosNoConfiables;
    }

    public JMenuItem getjMnUbiLibro() {
        return jMnUbiLibro;
    }

    public JMenuItem getjMnNuevoSocio() {
        return jMnNuevoSocio;
    }

    public JTextField getjTxtBuscar() {
        return jTxtBuscar;
    }

   
    
   

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMnIngresarLibro;
    private javax.swing.JMenuItem jMnIngresarUs;
    private javax.swing.JMenuItem jMnListaSocio;
    private javax.swing.JMenuItem jMnNuevoSocio;
    private javax.swing.JMenuItem jMnPrestarLibro;
    private javax.swing.JMenuItem jMnSociosNoConfiables;
    private javax.swing.JMenuItem jMnUbiLibro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtBuscar;
    // End of variables declaration//GEN-END:variables
}
