/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;



import javax.swing.JMenuItem;


/**
 *
 * @author Gabriela
 */
public class Biblioteca1 extends javax.swing.JFrame {
    
    public Biblioteca1() { 
         initComponents();

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnListaSocio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMnPrestarLibro = new javax.swing.JMenuItem();
        jMnIngresarLibro = new javax.swing.JMenuItem();
        jMnUbiLibro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 191, 125));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.setToolTipText("");
        jPanel1.setAutoscrolls(true);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 3, 48)); // NOI18N
        jLabel1.setText("Biblioteca B.G");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        jTextField1.setBackground(new java.awt.Color(237, 187, 135));
        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 500, 40));

        jButton1.setBackground(new java.awt.Color(241, 169, 89));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 110, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\braya\\Documents\\NetBeansProjects\\AF-AsimbayaBryan-Biblioteca\\src\\main\\java\\Imagenes\\Biblio.jpg")); // NOI18N
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 454));

        jMenuBar1.setBackground(new java.awt.Color(241, 169, 89));

        jMenu1.setBackground(new java.awt.Color(247, 191, 125));
        jMenu1.setText("Usuario");

        jMnListaSocio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnListaSocio.setText("Conocer Lista de socios");
        jMnListaSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnListaSocioActionPerformed(evt);
            }
        });
        jMenu1.add(jMnListaSocio);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(247, 191, 125));
        jMenu2.setText("Libro");

        jMnPrestarLibro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnPrestarLibro.setText("Prestar Libro");
        jMenu2.add(jMnPrestarLibro);

        jMnIngresarLibro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnIngresarLibro.setText("Ingresar Libro");
        jMenu2.add(jMnIngresarLibro);

        jMnUbiLibro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnUbiLibro.setText("Ubicacion Libro");
        jMnUbiLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnUbiLibroActionPerformed(evt);
            }
        });
        jMenu2.add(jMnUbiLibro);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnListaSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnListaSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnListaSocioActionPerformed

    private void jMnUbiLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnUbiLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnUbiLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biblioteca1().setVisible(true);
            }
        });
    }

   

    public JMenuItem getjMnIngresarLibro() {
        return jMnIngresarLibro;
    }

    public JMenuItem getjMnListaSocio() {
        return jMnListaSocio;
    }

 

    public JMenuItem getjMnPrestarLibro() {
        return jMnPrestarLibro;
    }

    public JMenuItem getjMnUbiLibro() {
        return jMnUbiLibro;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnIngresarLibro;
    private javax.swing.JMenuItem jMnListaSocio;
    private javax.swing.JMenuItem jMnPrestarLibro;
    private javax.swing.JMenuItem jMnUbiLibro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
