/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JMenuItem;

/**
 *
 * @author Gabriela
 */
public class Biblioteca1 extends javax.swing.JFrame {

    /**
     * Creates new form Biblioteca
     */
    public Biblioteca1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnCrearUsuario = new javax.swing.JMenuItem();
        jMnLogIn = new javax.swing.JMenuItem();
        jMnListaSocio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMnPrestarLibro = new javax.swing.JMenuItem();
        jMnIngresarLibro = new javax.swing.JMenuItem();
        jMnUbiLibro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setText("BIBLIOTECA BG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jMenu1.setText("Usuario");

        jMnCrearUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnCrearUsuario.setText("Crear Usuario");
        jMenu1.add(jMnCrearUsuario);

        jMnLogIn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnLogIn.setText("Log In");
        jMenu1.add(jMnLogIn);

        jMnListaSocio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnListaSocio.setText("Conocer Lista de socios");
        jMnListaSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnListaSocioActionPerformed(evt);
            }
        });
        jMenu1.add(jMnListaSocio);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Libro");

        jMnPrestarLibro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnPrestarLibro.setText("Prestar Libro");
        jMenu2.add(jMnPrestarLibro);

        jMnIngresarLibro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnIngresarLibro.setText("Ingresar Libro");
        jMenu2.add(jMnIngresarLibro);

        jMnUbiLibro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnUbiLibro.setText("Ubicacion Libro");
        jMnUbiLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnUbiLibroActionPerformed(evt);
            }
        });
        jMenu2.add(jMnUbiLibro);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnListaSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnListaSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnListaSocioActionPerformed

    private void jMnUbiLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnUbiLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnUbiLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biblioteca1().setVisible(true);
            }
        });
    }

    public JMenuItem getjMnCrearUsuario() {
        return jMnCrearUsuario;
    }

    public JMenuItem getjMnIngresarLibro() {
        return jMnIngresarLibro;
    }

    public JMenuItem getjMnListaSocio() {
        return jMnListaSocio;
    }

    public JMenuItem getjMnLogIn() {
        return jMnLogIn;
    }

    public JMenuItem getjMnPrestarLibro() {
        return jMnPrestarLibro;
    }

    public JMenuItem getjMnUbiLibro() {
        return jMnUbiLibro;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnCrearUsuario;
    private javax.swing.JMenuItem jMnIngresarLibro;
    private javax.swing.JMenuItem jMnListaSocio;
    private javax.swing.JMenuItem jMnLogIn;
    private javax.swing.JMenuItem jMnPrestarLibro;
    private javax.swing.JMenuItem jMnUbiLibro;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
